### ISSUE TITLE
On resolving a conflicted PR branch, the whole repo essentially crashes

### ISSUE THREAD

**Issue by 7db9a** [turbo-src/turbo-src#143]

**Comment by 7db9a** [comment]
a. An e2e conflict resolution test (7db9a).

b. Let's try to search childDefaultHash in the engine when voting on LinkedPullRequest (solves, live with it).

~~Create a conflictResolution e2e test in turbosrc-service. (source of truth on mergeability is Github).~~

c. Make sure we have a "conflictResolution" test on the turbosrc-engine.

**Comment by tester15tsrc** [comment]
Recent work on e2e-conflict-test branch is promising. The conflict state appears to work now, yielding good results on extension testing, but more testing is needed.

**Comment by 7db9a** [comment]
Resolved with push `d2c6a58ea7be50f198daa4377d9826b80e3910ff`

**Comment by 7db9a** [comment]
Unfortunately, github actions fails as it disallows updating the testers demo branches with they key. We'd have to add a Github Secret to actions. However, local testing is automated to the point where github actions is redundant. Also, Github Actions is a potential footgun for various reasons. It's served it's purpose and if it's brought back it would likely run against our a private runner.
