### ISSUE TITLE
There is no GH service that maps issueID to tsrcID

### ISSUE THREAD

**Issue by 7db9a** [turbo-src/turbo-src#17]
We need a service that has only 2 endpoints. Final piece of puzzle that makes Turbosrc truly cross-platform.

add(tsrcID, issueID)

getTsrcID(issueID) -> tsrcID

**Comment by JeffreyLWood** [comment]
repo = String, unique to universe
tsrcID = String, unique to repo
issueId = String, unique to repo

Can't add an identical entry
TsrcID unique to repo but not unique universally
IssueId ^


add(repo, tsrcID, issueID)

getTsrcID(repo, issueID) => return tsrcID

getIssueID(repo, tsrcID) => issueID

**Comment by JeffreyLWood** [comment]
Here is gh-service:

https://github.com/turbo-src/gh-service
