### ISSUE TITLE
Rename subsystems

### ISSUE THREAD

**Issue by 7db9a** [turbo-src/turbo-src#21]
Rename repos subsystems to new names.

**Comment by 7db9a** [comment]
Also the readme on master branch here in this repo needs to reflect new names for subsystems

**Comment by JeffreyLWood** [comment]
Renaming of repos complete. On the readme, I left out "Reibase" as I thought it was distracting from the funcitonality of the sub service. Let me know what you want to do.
![Screen Shot 2022-11-05 at 9 38 17 AM](https://user-images.githubusercontent.com/75996017/200122698-e523005c-245c-410d-bbda-9121cb0ce12c.png)
