### ISSUE TITLE
We don't have a neon postrgres endpoint

### ISSUE THREAD

**Issue by 7db9a** [turbo-src/turbo-src#22]
Refactor a single sub-service to use a neon endpoint.

Base the refactor off alpha branch, after standing up a new cloud cluster.

**Comment by JeffreyLWood** [comment]
The following tasks have been completed:

- The branches called alpha across all services query the new Fly.io account
- The branch called alpha-neon on turbosrc-reibase-namespace queries a Neon.tech Postgres database and is deployed at turbosrc-reibase-namespace.fly.dev/graphql
