### ISSUE TITLE
Install and initialization not tested on fresh environment.

### ISSUE THREAD

**Issue by 7db9a** [turbo-src/turbo-src#53]
Once it complained the gihtub-maker-tools image was not found, even though it was in the docker-compose.yml.

**Comment by ramirc5** [comment]
FYI: In the tsrc test script, docker command for create pull request should be for docker-compose. If someone runs it, they might run into an error as its looking for an image which doesn't exist.

**Comment by 7db9a** [comment]
Tested and works.
