### ISSUE TITLE
Bug: Votes in modal are out of order after 1 min

### ISSUE THREAD

**Issue by jex441** [turbo-src/turbo-src#87]
<img width="649" alt="Screenshot 2023-09-21 at 3 52 15 PM" src="https://github.com/turbo-src/turbo-src/assets/75996017/c522edc5-4749-4604-b303-43d68ccf5058">

The votes should be ordered from newest to oldest. Currently as seen above they go from oldest to newest. This does not occur when they are seconds old, only when they turn to minutes in age.

Check the res from getVotes which is seeding the table. See if they are in order or not. If they are, then it is a front end issue.

If they are not, then check turbosrc-engine/lib/getVotes to see if they are being selected from the Postgres table in the correct order.

**Comment by 7db9a** [comment]
Closed with PR #96 merge.
